{"code": " df1.merge(df2, on=\"id\")", "compilation_passed": true, "time": 0.0032601356506347656, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat([df1, df2], ignore_index=True)", "compilation_passed": true, "time": 0.0029408931732177734, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, how=\"inner\", on=\"id\")", "compilation_passed": true, "time": 0.002929210662841797, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat((df1, df2), axis=0)", "compilation_passed": true, "time": 0.003052234649658203, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, on='id', how='inner')", "compilation_passed": true, "time": 0.002841949462890625, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2, on=\"id\", how=\"inner\")", "compilation_passed": true, "time": 0.0028810501098632812, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat([df1, df2])", "compilation_passed": true, "time": 0.0028679370880126953, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2, on=\"id\", suffixes=(\"_1\", \"_2\"), how=\"inner\")", "compilation_passed": true, "time": 0.0028421878814697266, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, on=\"id\", how=\"inner\")", "compilation_passed": true, "time": 0.002866029739379883, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat([df1, df2], axis=0)", "compilation_passed": true, "time": 0.0028259754180908203, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, on='id')", "compilation_passed": true, "time": 0.0029261112213134766, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2)", "compilation_passed": true, "time": 0.0028281211853027344, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2, on=\"id\")", "compilation_passed": true, "time": 0.002852201461791992, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, on='id', how='outer', indicator='_')", "compilation_passed": true, "time": 0.0028808116912841797, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2, on='id', how='inner')", "compilation_passed": true, "time": 0.002834320068359375, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat([df1, df2], axis=1)", "compilation_passed": true, "time": 0.002847909927368164, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.concat([df1, df2]).reset_index(drop=True)", "compilation_passed": true, "time": 0.0028128623962402344, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " df1.merge(df2, on=\"id\", how=\"left\")", "compilation_passed": true, "time": 0.002846240997314453, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.merge(df1, df2, on='id')", "compilation_passed": true, "time": 0.002855062484741211, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
