{"code": " pd.DataFrame(data, columns=foods, index=range(len(pairs)))", "compilation_passed": true, "time": 0.001313924789428711, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data, columns=foods)", "compilation_passed": true, "time": 0.0012791156768798828, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data)", "compilation_passed": true, "time": 0.0012941360473632812, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data, index=range(len(data)), columns=foods)", "compilation_passed": true, "time": 0.0012309551239013672, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data, columns=foods, index=[\"\"] * len(pairs))", "compilation_passed": true, "time": 0.0012469291687011719, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data=data, columns=foods)", "compilation_passed": true, "time": 0.0011970996856689453, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data, columns=foods, index=np.arange(data.shape[0]))", "compilation_passed": true, "time": 0.0012340545654296875, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " pd.DataFrame(data=data)", "compilation_passed": true, "time": 0.0012400150299072266, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
