{"code": " coords = zip(*data)", "compilation_passed": true, "time": 0.05808115005493164, "tests_passed": false, "error": "<class 'property'> returned a result with an exception set"}
{"code": " coordinates = zip(*data)", "compilation_passed": true, "time": 0.0024242401123046875, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " features = zip(*data)", "compilation_passed": true, "time": 0.002429962158203125, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " X = zip(*data)", "compilation_passed": true, "time": 0.002408742904663086, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " coord = zip(*data)", "compilation_passed": true, "time": 0.0024073123931884766, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " xs, ys = list(), list(), list()", "compilation_passed": true, "time": 0.002424001693725586, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " coord = list(), list()", "compilation_passed": true, "time": 0.002440214157104492, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " x, y = zip(*data)", "compilation_passed": true, "time": 0.0024220943450927734, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
{"code": " _ = zip(*data)", "compilation_passed": true, "time": 0.002443075180053711, "tests_passed": false, "error": "partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)"}
